##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5], dtype=int) # 1D array

In [ ]:
arr1.size # eleman sayısını verir

5

In [ ]:
arr1.ndim # boyut sayısını verir

1

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [ ]:
arr2 = np.array([[1,2,6,7],[4,3,9,5]], dtype=int) # 2D array
arr3 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]], dtype=int) # 3D array

In [10]:
arr2.ndim # boyut sayısını verir

2

In [11]:
arr2.size # eleman sayısını verir

8

In [ ]:
arr2.shape # boyut bilgilerini verir

(2, 4)

In [16]:
arr3.ndim # boyut sayısını verir

3

In [17]:
arr3.size # eleman sayısını verir

12

In [18]:
arr3.ndim # boyut sayısını verir

3

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [20]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arr2[0][1]

np.int64(2)

In [22]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
arr2[0][3]

np.int64(7)

In [29]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arr3[1][1][2]

np.int64(9)

In [32]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arr3[0][0][1]

np.int64(5)

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [35]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arr2[0][1:3]

array([2, 6])

In [38]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arr2[1][1:]

array([3, 9, 5])

In [41]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arr3[0][1]

array([21,  8, 11])

In [45]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arr3[1][0][1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [ ]:
eye1 = np.eye(5,3, dtype=int) # 5x3 birim matris
eye2 = np.eye(5,3, dtype=int) # 5x3 birim matris

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
np.vstack([eye1,eye2]) # dikey birleştirme

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [49]:
np.hstack([eye1,eye2]) # yatay birleştirme

array([[1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])