##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6], dtype="int")
print(f"Arr'in boyutu: {arr.shape} Eleman Sayısı: {arr.size} ")


Arr'in boyutu: (6,) Eleman Sayısı: 6 


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [21]:
import numpy as np

arr2 = np.array([[1,2,6,7],[4,3,9,5]])
arr3 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

print(f"Arr2'nin boyutu: {arr2.shape} Eleman sayısı: {arr2.size} Satır Sayısı: {arr2.shape[0]} Sütun Sayısı: {arr2.shape[1]}")
print(f"Arr3'ün boyutu: {arr3.shape} Eleman sayısı: {arr3.size} Satır Sayısı: {arr3.shape[1]} Sütun Sayısı: {arr3.shape[2]}")

Arr2'nin boyutu: (2, 4) Eleman sayısı: 8 Satır Sayısı: 2 Sütun Sayısı: 4
Arr3'ün boyutu: (2, 2, 3) Eleman sayısı: 12 Satır Sayısı: 2 Sütun Sayısı: 3


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [50]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
arr2[0][1]

np.int64(2)

In [49]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
arr2[0][3]

np.int64(7)

In [48]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
arr3[1][1][2]

np.int64(9)

In [47]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
arr3[0][0][1]

np.int64(5)

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [28]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
arr2[0][1:3]

array([2, 6])

In [30]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
arr2[1][1:]

array([3, 9, 5])

In [31]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
arr3[0][1:]

array([[21,  8, 11]])

In [32]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
arr3[1][0][1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [46]:
arr4 =np.array([[0,1,0],[0,1,1],[1,1,0],[1,1,1],[1,1,1]])
arr5 =np.array([[1, 0, 1],[1, 0, 0],[0, 0, 1],[0, 0, 0],[1, 0, 0]])

satir_birleş= np.vstack([arr4,arr5])
sütun_birleş= np.hstack([arr4,arr5])

print("Satır bazında birleşimi: ",satir_birleş,)
print("Sütun bazında birleşimi: ",sütun_birleş)


Satır bazında birleşimi:  [[0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]
 [1 1 1]
 [1 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 0]
 [1 0 0]]
Sütun bazında birleşimi:  [[0 1 0 1 0 1]
 [0 1 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 1 0 0 0]
 [1 1 1 1 0 0]]
